name: Test S3 CloudFormation Deployment

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-s3-localstack.yaml'
      - 'templates/s3-bucket.yaml'
  pull_request:

jobs:
  test-s3-localstack:
    runs-on: ubuntu-latest
    env:
      LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup LocalStack
        uses: LocalStack/setup-localstack@v0.3.2
        with:
          image-tag: 'latest'
          install-awslocal: 'true'

      - name: Deploy CloudFormation template
        run: |
          awslocal cloudformation deploy \
            --stack-name test-s3-stack \
            --template-file templates/s3-bucket.yaml

      - name: Validate deployment
        run: |
          echo "Listing buckets:"
          awslocal s3 ls

          echo "Confirming the new S3 bucket exists:"
          awslocal s3api list-buckets | grep "my-localstack-test-bucket"
